name: run-tests
on: [push]
jobs: 
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: |
          touch .env
          echo GOREST_BEARER_TOKEN=${{secrets.GOREST_BEARER_TOKEN}} >> .env
      - run: npm i
      - run: npm test